spring:
  thymeleaf:
    prefix: classpath:/view/  # Path to your Thymeleaf templates (adjust as needed)
    suffix: .html                  # Suffix for your Thymeleaf templates (usually .html)
    mode: HTML5                   # Template mode (HTML5 is recommended)
    encoding: UTF-8                # Character encoding for templates (UTF-8 is common)
    cache: true                    # Enable template caching (improve performance)
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret:  
  datasource:
    url: jdbc:h2:file:./data/mydatabase
    username: test
    password: test
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE